trigger: none

pool:
  name: $(pool)

variables:
  - group: New variable group 22-Apr

  - name: WorkDir
    value: '$(System.DefaultWorkingDirectory)/env/dev'

stages:
  - stage: build
    jobs:
      - job: 
        steps:
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: 'mvn clean package'