trigger: none

pool:
  name: $(pool)

variables:
  - group: New variable group 22-Apr

stages:
- stage: Build
  jobs:
  - job: MavenBuild
    steps:

    - task: PowerShell@2
      displayName: Check Java and Maven
      inputs:
        targetType: 'inline'
        script: |
          echo $env:JAVA_HOME
          java -version
          mvn --version

    - task: PowerShell@2
      displayName: Maven Build
      inputs:
        targetType: 'inline'
        workingDirectory: '$(System.DefaultWorkingDirectory)/JavaLoginPage'
        script: |
          mvn clean package