trigger: none

parameters:
- name: terraformCommand
  type: string
  default: plan
  values:
    - init
    - validate
    - fmt
    - plan
    - apply

pool:
  name: $(pool)

variables:
- group: New variable group 22-Apr

- name: WorkDir
  value: '$(System.DefaultWorkingDirectory)/env/dev'

steps:

# ---------------- CODE CHECKOUT ----------------
- checkout: self
  clean: true

# ---------------- TERRAFORM INIT ----------------
- task: TerraformTask@5
  displayName: "Terraform Init"
  condition: in('${{ parameters.terraformCommand }}','init','validate','fmt','plan','apply')
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(WorkDir)'
    backendServiceArm: 'Taskify-SC'
    backendAzureRmResourceGroupName: 'rg-pip'
    backendAzureRmStorageAccountName: 'strpipeline123'
    backendAzureRmContainerName: 'containerpipeline'
    backendAzureRmKey: 'keystatefile1'

# ---------------- VALIDATE ----------------
- task: TerraformTask@5
  displayName: "Terraform Validate"
  condition: in('${{ parameters.terraformCommand }}','init','validate','fmt','plan','apply')
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(WorkDir)'

# ---------------- FORMAT CHECK ----------------
- task: TerraformTask@5
  displayName: "Terraform Format Check"
  condition: in('${{ parameters.terraformCommand }}','init','validate','fmt','plan','apply')
  inputs:
    provider: 'azurerm'
    command: 'custom'
    workingDirectory: '$(WorkDir)'
    customCommand: 'fmt'
    outputTo: 'console'

# ---------------- LINT (CODE LEVEL) ----------------
- task: PowerShell@2
  displayName: "TFLint Code Check"
  condition: in('${{ parameters.terraformCommand }}','init','validate','fmt','plan','apply')
  inputs:
    targetType: 'inline'
    script: |
      tflint --recursive

# ---------------- SECURITY SCAN ----------------
- task: PowerShell@2
  displayName: "Checkov Security Scan"
  condition: in('${{ parameters.terraformCommand }}','init','validate','fmt','plan','apply')
  inputs:
    targetType: 'inline'
    script: |
      pip install checkov
      checkov -d $(WorkDir) --framework terraform --soft-fail -o cli > checkov-report.txt

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'checkov-report.txt'
    artifactName: 'checkov-report'

# ---------------- PLAN ----------------
- task: TerraformTask@5
  displayName: "Terraform Plan"
  condition: in('${{ parameters.terraformCommand }}','init','validate','fmt','plan','apply')
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(WorkDir)'
    environmentServiceNameAzureRM: 'Taskify-SC'

# ---------------- APPLY ----------------
- task: TerraformTask@5
  displayName: "Terraform Apply"
  condition: eq('${{ parameters.terraformCommand }}','apply')
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(WorkDir)'
    commandOptions: '-auto-approve'
    environmentServiceNameAzureRM: 'Taskify-SC'