trigger: none

parameters:
- name: branchName
  displayName: Select Branch
  type: string
  default: main

- name: terraformCommand
  displayName: Select Terraform Command
  type: string
  default: init
  values:
    - init
    - validate
    - fmt
    - plan
    - apply

pool:
  name: $(pool)   # global/variable pipeline

variables:
- group: New variable group 22-Apr

- name: WorkDir
  value: '$(System.DefaultWorkingDirectory)/env/dev' # pipeline variable

stages:
  - stage: Build
    displayName: buildstage
    jobs:
      - job: TerraformInittoPlan
        displayName: "terraform Init to plan"
        steps:
        - checkout: self

        - task: TerraformTask@5
          displayName: "Init"
          condition: eq('${{ parameters.terraformCommand }}','init')
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(WorkDir)'
            backendServiceArm: 'Taskify-SC'
            backendAzureRmResourceGroupName: 'rg-pip'
            backendAzureRmStorageAccountName: 'strpipeline123'
            backendAzureRmContainerName: 'containerpipeline'
            backendAzureRmKey: 'keystatefile1'

        - task: TerraformTask@5
          displayName: "validate"
          condition: or(
                      eq('${{ parameters.terraformCommand }}','init'),
                      eq('${{ parameters.terraformCommand }}','validate')
                    )
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: '$(WorkDir)'

        - task: TerraformTask@5
          displayName: "FMT"
          condition: or(
                      eq('${{ parameters.terraformCommand }}','init'),
                      eq('${{ parameters.terraformCommand }}','validate'),
                      eq('${{ parameters.terraformCommand }}','fmt')
                    )
          inputs:
            provider: 'azurerm'
            command: 'custom'
            workingDirectory: '$(WorkDir)'
            outputTo: 'console'
            customCommand: 'fmt'
            environmentServiceNameAzureRM: 'Taskify-SC'

        - task: TerraformTask@5
          displayName: "Plan"
          condition: or(
                    eq('${{ parameters.terraformCommand }}','init'),
                    eq('${{ parameters.terraformCommand }}','validate'),
                    eq('${{ parameters.terraformCommand }}','fmt'),
                    eq('${{ parameters.terraformCommand }}','plan')
                  )
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(WorkDir)'
            environmentServiceNameAzureRM: 'Taskify-SC'

  - stage: 
    displayName: Scanning
    jobs:
      - job: SecurityScanning
        displayName: 'SecurityScanning'
        steps:
          - task: tfsec@1
            inputs:
              version: 'v1.26.0'
              dir: '$(System.DefaultWorkingDirectory)'

  - stage: 
    displayName: Mail
    jobs:
      - job: mail
        displayName: mail
        steps:
        - task: su-sendgrid@0
          inputs:
            SendGridAPIKey: 'OR7056f5cbfa4aa3131f869a27dd3d4277'
            senderEmailAddress: 'shrutibawase01@gmail.com'
            recipientEmailAddress: 'shrutibawase01@gmail.com'
            emailSubject: 'Tfsec Security Report'
            emailBody: 'Text'

  - stage: Deploy
    displayName: Deploy
    jobs:
      # - job: ManualValidation
      #   displayName: "Manual Validation"
      #   # dependsOn: TerraformInittoPlan
      #   pool: server
      #   steps:
      #   - task: ManualValidation@1
      #     inputs:
      #       notifyUsers: 'shrutibawase01@gmail.com'
      #       approvers: 'shrutibawase01@gmail.com'

      - job: TerraformApply
        displayName: "Apply"
        condition: eq('${{ parameters.terraformCommand }}', 'apply')
        # dependsOn: ManualValidation
        pool: 
          name: '$(pool)'
        steps:

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(WorkDir)'
              backendServiceArm: 'Taskify-SC'
              backendAzureRmResourceGroupName: 'rg-pip'
              backendAzureRmStorageAccountName: 'strpipeline123'
              backendAzureRmContainerName: 'containerpipeline'
              backendAzureRmKey: 'keystatefile1'

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(WorkDir)'
              commandOptions: '-auto-approve'
              environmentServiceNameAzureRM: 'Taskify-SC'