trigger: none

pool:
  name: $(pool)

variables:
- group: New variable group 22-Apr

stages:

# =========================
# BUILD STAGE
# =========================
- stage: Build
  displayName: Build WAR

  jobs:
  - job: MavenBuild

    steps:

    - task: PowerShell@2
      displayName: Maven Build
      inputs:
        targetType: 'inline'
        workingDirectory: '$(System.DefaultWorkingDirectory)\JavaLoginPage'
        script: |

          $env:JAVA_HOME="D:\Shruti\Tools\Eclipse Adoptium\jdk-17.0.17.10-hotspot"

          $env:PATH="$env:JAVA_HOME\bin;D:\Shruti\Tools\apache-maven-3.9.12\bin;$env:PATH"

          java -version
          mvn -version

          mvn clean package

    - task: PublishBuildArtifacts@1
      displayName: Publish WAR
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)\JavaLoginPage\target'
        ArtifactName: 'java-war'
        publishLocation: 'Container'


# =========================
# DEPLOY STAGE
# =========================
- stage: Deploy
  displayName: Deploy to Tomcat
  dependsOn: Build

  jobs:
  - job: DeployWAR

    steps:

    - download: current
      artifact: java-war

    # Stop Tomcat Service
    - task: PowerShell@2
      displayName: Stop Tomcat Service
      inputs:
        targetType: 'inline'
        script: |

          net stop Tomcat9

          Start-Sleep -Seconds 10

    # Remove Old WAR
    - task: PowerShell@2
      displayName: Remove Old WAR
      inputs:
        targetType: 'inline'
        script: |

          Remove-Item `
          "D:\Shruti\Tools\apache-tomcat-9.0.118\webapps\JavaLoginShowcase*" `
          -Recurse -Force -ErrorAction SilentlyContinue

    # Copy New WAR
    - task: PowerShell@2
      displayName: Copy WAR
      inputs:
        targetType: 'inline'
        script: |

          Copy-Item `
          "$(Pipeline.Workspace)\java-war\*.war" `
          "D:\Shruti\Tools\apache-tomcat-9.0.118\webapps\" `
          -Force

    # Start Tomcat Service
    - task: PowerShell@2
      displayName: Start Tomcat Service
      inputs:
        targetType: 'inline'
        script: |

          net start Tomcat9

          Start-Sleep -Seconds 20

    # Verify Deployment
    - task: PowerShell@2
      displayName: Verify Deployment
      inputs:
        targetType: 'inline'
        script: |

          netstat -ano | findstr 8080

          Write-Host ""
          Write-Host "Application URL:"
          Write-Host "http://localhost:8080"